### ISSUE TITLE
After creating a new doc and saving, "Type" should be readonly

### ISSUE THREAD

**Issue by joshwnj** [joshwnj/team-index#15]
This is only an issue immediately after saving. If you refresh the page and reload the doc, you get the correct behaviour ("Type" field is readonly).

**Comment by lfilho** [comment]
@joshwnj, Related question: after "loading" an unexisting ID (i.e. the create new doc form), the ID field keeps writeable. Shouldn't we make it readonly from that moment on? Consider this scenario:

1. Enter wiki.
2. Type "lfilho" in the ID filed and hit Load.
3. That ID doesn't exist, so we're now on create mode
4. I decide to change "lfilho" to "luiz.filho"
5. Note that since we're on "create mode" the type field is still editable, so what happens if "luiz.filho" existed already? What is the intended behaviour? I presume we shouldn't allow this and just prevent the user from changing the ID once the create form was loaded. Am I right in my way of thinking?

Thanks

**Comment by lfilho** [comment]
Oh. "I'm on it" on this one too (regardless of your answer to my previous comment :) )

**Comment by joshwnj** [comment]
Good point - let's make it readonly at this point like you said.
